table 'Exemplo Aquisição'
	lineageTag: 1195ffdc-3138-4d63-bb0c-265702a20fa3

	column Dono
		dataType: string
		lineageTag: 8c10e010-9493-4263-af13-45296c708233
		summarizeBy: none
		sourceColumn: Dono

		annotation SummarizationSetBy = Automatic

	column Ativo
		dataType: string
		lineageTag: 70ff9aea-2fbc-492b-bb88-9857451f4e85
		summarizeBy: none
		sourceColumn: Ativo

		annotation SummarizationSetBy = Automatic

	column 'Preço de Aquisição'
		dataType: double
		lineageTag: ef1a7d0f-e18f-451d-88b4-83f396d744ca
		summarizeBy: sum
		sourceColumn: Preço de Aquisição

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Número de Cotas'
		dataType: int64
		formatString: 0
		lineageTag: f5a80fb3-d365-4be7-b2da-7fd8dc291014
		summarizeBy: sum
		sourceColumn: Número de Cotas

		annotation SummarizationSetBy = Automatic

	column 'Data de Aquisição'
		dataType: dateTime
		formatString: Short Date
		lineageTag: b7fe73bb-d37d-488a-83a9-019951e41407
		summarizeBy: none
		sourceColumn: Data de Aquisição

		variation Variation
			isDefault
			relationship: ec93efc9-3757-4e72-b7f1-5bef920dbac4
			defaultHierarchy: LocalDateTable_426fa909-23bf-4417-a2f4-6aa7e3d78c57.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'Exemplo Aquisição' = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\luis.nascimento\Documents\Análises Financeiras\Exemplo Aquisição.csv"),[Delimiter=",", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Dono", type text}, {"Ativo", type text}, {"Preço de Aquisição", type number}, {"Número de Cotas", Int64.Type}, {"Data de Aquisição", type date}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

