table 'FIIs rendimentos por data (2021-2025)'
	lineageTag: 99fe8725-f98a-4222-bf79-a70d68c6bccb

	column ATIVO
		dataType: string
		lineageTag: 0e8838d6-0444-4503-9acd-aa724d4f0c26
		summarizeBy: none
		sourceColumn: ATIVO

		annotation SummarizationSetBy = Automatic

	column VALOR
		dataType: double
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: c87c4cf2-6bc8-41f4-aa24-9fab9fb9c705
		summarizeBy: sum
		sourceColumn: VALOR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column 'DATA COM'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7a437a2a-64b8-42b4-83e8-638b65bc99a9
		summarizeBy: none
		sourceColumn: DATA COM

		variation Variation
			isDefault
			relationship: 65d265df-5d39-427f-ad63-1674305790da
			defaultHierarchy: LocalDateTable_d3663bd9-96f4-4764-bbaf-6be066d46774.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'DATA PAGAMENTO'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 425fdc29-7de3-4028-8358-08b0b6ffe865
		summarizeBy: none
		sourceColumn: DATA PAGAMENTO

		variation Variation
			isDefault
			relationship: 9a3e48c4-835a-4917-991d-67c740bbe3bc
			defaultHierarchy: LocalDateTable_697dfe4d-403c-4b64-be53-4c060bec5b59.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TIPO
		dataType: string
		lineageTag: d1c2578a-b394-4368-8b36-3717bbbccadb
		summarizeBy: none
		sourceColumn: TIPO

		annotation SummarizationSetBy = Automatic

	column DY
		dataType: double
		lineageTag: 1264eaf1-6c31-4b22-bba7-98631c05ff73
		summarizeBy: sum
		sourceColumn: DY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'FIIs rendimentos por data (2021-2025)' = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\luis.nascimento\Documents\Análises Financeiras\Dados Modelados\FIIs rendimentos por data (2021-2025).csv"),[Delimiter=",", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"ATIVO", type text}, {"VALOR", type number}, {"DATA COM", type date}, {"DATA PAGAMENTO", type date}, {"TIPO", type text}, {"DY", type number}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

