table historico_Fii
	lineageTag: 5301579b-ec3c-4c16-880a-a28d2a61bea0

	column open
		dataType: double
		lineageTag: 35969804-83a0-4f99-874f-12e1f0a0172b
		summarizeBy: sum
		sourceColumn: open

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column high
		dataType: double
		lineageTag: 55ad8d46-9d7f-45f7-ac6e-21175ad9e740
		summarizeBy: sum
		sourceColumn: high

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column low
		dataType: double
		lineageTag: d95a5a15-ebcb-4185-a0a1-1a8b06b68aac
		summarizeBy: sum
		sourceColumn: low

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column close
		dataType: double
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: d9a0b857-5c53-46fb-ab00-e5c172fb4acc
		summarizeBy: sum
		sourceColumn: close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column volume
		dataType: double
		lineageTag: ebab23eb-683b-42c2-bd0d-32c1d30f046a
		summarizeBy: sum
		sourceColumn: volume

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column adjclose
		dataType: double
		lineageTag: 5fc19449-fe8c-4701-b40e-643ef94ec21a
		summarizeBy: sum
		sourceColumn: adjclose

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column dividends
		dataType: double
		lineageTag: 2ec8d2d8-74c8-4047-aeed-3df78759a7f8
		summarizeBy: sum
		sourceColumn: dividends

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column splits
		dataType: double
		lineageTag: 2b653119-194f-481b-af68-3d0ec0e46985
		summarizeBy: sum
		sourceColumn: splits

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Ativo
		dataType: string
		lineageTag: 1d5830f2-d0a5-407f-b049-91ae9b29d337
		summarizeBy: none
		sourceColumn: Ativo

		annotation SummarizationSetBy = Automatic

	column Data
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2d9ebd96-7bb9-49a0-b6bc-4c5269b66716
		summarizeBy: none
		sourceColumn: Data

		variation Variation
			isDefault
			relationship: 3f4aa6be-2c33-4ee5-9b22-9165c11f79c2
			defaultHierarchy: LocalDateTable_60dbead0-088b-4f33-8fcd-adcf5c5f9957.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition historico_Fii = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\luis.nascimento\Documents\Análises Financeiras\Dados Modelados\historico_Fii.csv"),[Delimiter=",", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Valor Substituído" = Table.ReplaceValue(#"Cabeçalhos Promovidos",".",",",Replacer.ReplaceText,{"open", "high", "low", "close", "volume", "adjclose", "dividends", "splits"}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Valor Substituído",{{"open", type number}, {"high", type number}, {"low", type number}, {"close", type number}, {"volume", type number}, {"adjclose", type number}, {"dividends", type number}, {"splits", type number}}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Tipo Alterado1",{{"Data", type date}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

