table 'Dividendos pagos por data (2021-2025)'
	lineageTag: 32b115a9-0f0f-46b6-a4da-dda4168d403a

	column ATIVO
		dataType: string
		lineageTag: d09eaccd-4b05-425a-ad35-587060434f5c
		summarizeBy: none
		sourceColumn: ATIVO

		annotation SummarizationSetBy = Automatic

	column VALOR
		dataType: double
		formatString: 0.00
		lineageTag: e86a4d2a-098c-463f-b255-cc8f333a5983
		summarizeBy: sum
		sourceColumn: VALOR

		annotation SummarizationSetBy = Automatic

	column 'DATA COM'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 3ada64d1-933c-4412-811e-8cd97664c046
		summarizeBy: none
		sourceColumn: DATA COM

		variation Variation
			isDefault
			relationship: 1f57eab7-b53e-4a7d-bf55-800b57ae4f4a
			defaultHierarchy: LocalDateTable_b3bfa959-b5f7-41e3-9a4d-3a23c7df7937.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'DATA PAGAMENTO'
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 05d8e564-04cf-4734-8586-7876feed3297
		summarizeBy: none
		sourceColumn: DATA PAGAMENTO

		variation Variation
			isDefault
			relationship: 035b81e1-7e7e-4811-992e-9d86bd48a222
			defaultHierarchy: LocalDateTable_f6f1966f-3dcf-4fc9-baa0-ec9e2829b0a7.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column TIPO
		dataType: string
		lineageTag: 26913228-fe84-4dff-b267-9521149cbbb1
		summarizeBy: none
		sourceColumn: TIPO

		annotation SummarizationSetBy = Automatic

	column DY
		dataType: double
		lineageTag: 4598fa83-72ac-4a5e-91bc-fbe9824a6146
		summarizeBy: sum
		sourceColumn: DY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AnoMes = FORMAT ('Dividendos pagos por data (2021-2025)'[DATA PAGAMENTO], "YYYY-MM")
		lineageTag: 01fed3e7-76cd-4a67-b488-d0cdd8e5f9ac
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Dividendos pagos por data (2021-2025)' = m
		mode: import
		queryGroup: 'Tabelas Dimensão'
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\luis.nascimento\Documents\Análises Financeiras\Dados Modelados\Dividendos pagos por data (2021-2025).csv"),[Delimiter=",", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Valor Substituído" = Table.ReplaceValue(#"Cabeçalhos Promovidos",".",",",Replacer.ReplaceText,{"DY"}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Valor Substituído",{{"DY", type number}}),
				    #"Valor Substituído1" = Table.ReplaceValue(#"Tipo Alterado1",".",",",Replacer.ReplaceText,{"VALOR"}),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Valor Substituído1",{{"VALOR", type number}}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Tipo Alterado2",{{"ATIVO", type text}, {"VALOR", type number}, {"DATA COM", type date}, {"DATA PAGAMENTO", type date}, {"TIPO", type text}, {"DY", type number}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

